export const COLOR_PRIMARY_BUTTON = '#FFBC00'
export const COLOR_PRIMARY_BUTTON_SHADOW = '#D9AA26'
export const COLOR_SUCC_BUTTON = '#65ff00'
export const COLOR_SUCC_BUTTON_SHADOW = '#6dd926'
export const COLOR_ERR_BUTTON = '#ff4500'
export const COLOR_ERR_BUTTON_SHADOW = '#d95626'
export const COLOR_TITLE_TEXT = 'black'
export const COLOR_INPUT_BACKGROUND = 'rgba(142, 142, 147, 0.21)'
