version: 2
jobs:
  build:
    docker:
      - image: circleci/node:8

    working_directory: ~/github

    steps:
      - checkout

      - restore_cache:
          keys:
            - v1-dependencies-{{ checksum "package.json" }}
            # fallback to using the latest cache if no exact match is found
            - v1-dependencies-

      - run: yarn install

      - save_cache:
          key: v1-dependencies-{{ checksum "package.json" }}
          paths:
            - node_modules

      - run: yarn lint:js
      - run: yarn lint:styles

      - run: yarn test
